// <auto-generated />
using System;
using Heinekamp.PgDb.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Heinekamp.PgDb.Migrations
{
    [DbContext(typeof(PgContext))]
    partial class PgContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Heinekamp.Domain.Models.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DownloadsCount")
                        .HasColumnType("bigint");

                    b.Property<int>("FileTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FileTypeId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Heinekamp.Domain.Models.DownloadLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("DownloadLinks");
                });

            modelBuilder.Entity("Heinekamp.Domain.Models.FileType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FileTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Extension = "",
                            IconFileName = "empty.svg"
                        },
                        new
                        {
                            Id = 2,
                            Extension = ".doc",
                            IconFileName = "doc.svg"
                        },
                        new
                        {
                            Id = 3,
                            Extension = ".docx",
                            IconFileName = "doc.svg"
                        },
                        new
                        {
                            Id = 4,
                            Extension = ".gif",
                            IconFileName = "gif.svg"
                        },
                        new
                        {
                            Id = 5,
                            Extension = ".jpg",
                            IconFileName = "jpg.svg"
                        },
                        new
                        {
                            Id = 6,
                            Extension = ".pdf",
                            IconFileName = "pdf.svg"
                        },
                        new
                        {
                            Id = 7,
                            Extension = ".png",
                            IconFileName = "png.svg"
                        },
                        new
                        {
                            Id = 8,
                            Extension = ".svg",
                            IconFileName = "svg.svg"
                        },
                        new
                        {
                            Id = 9,
                            Extension = ".txt",
                            IconFileName = "txt.svg"
                        },
                        new
                        {
                            Id = 10,
                            Extension = ".xls",
                            IconFileName = "xls.svg"
                        },
                        new
                        {
                            Id = 11,
                            Extension = ".xlsx",
                            IconFileName = "xls.svg"
                        },
                        new
                        {
                            Id = 12,
                            Extension = ".jpeg",
                            IconFileName = "jpg.svg"
                        });
                });

            modelBuilder.Entity("Heinekamp.Domain.Models.Document", b =>
                {
                    b.HasOne("Heinekamp.Domain.Models.FileType", "FileType")
                        .WithMany()
                        .HasForeignKey("FileTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FileType");
                });

            modelBuilder.Entity("Heinekamp.Domain.Models.DownloadLink", b =>
                {
                    b.HasOne("Heinekamp.Domain.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");
                });
#pragma warning restore 612, 618
        }
    }
}
